FROM node:15.14-alpine
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

ENV DEBUG=learn-studio-api:*
COPY ["package.json", "package-lock.json*", "./"]

RUN npm ci
COPY . .
ENTRYPOINT [ "npm", "start" ]